from typing import Literal

SagBaseFields = Literal[
    "id",
    "kategoriid" "lovnummer",
    "lovnummerdato",
    "nummer",
    "nummernumerisk",
    "nummerpostfix",
    "nummerprefix",
    "opdateringsdato",
    "offentlighedskode",
    "paragraf",
    "paragrafnummer",
    "periodeid",
    "afgørelse",
    "afgørelsesdato",
    "afgørelsesresultatkode",
    "afstemningskonklusion",
    "baggrundsmateriale",
    "begrundelse",
    "deltundersagid",
    "fremsatundersagid",
    "resume",
    "retsinformationsurl",
    "rådsmødedato",
    "statsbudgetsag",
    "statusid",
    "titel",
    "titelkort",
    "typeid",
]
